### ISSUE TITLE
Could not regenerate the training data

### ISSUE THREAD

**Issue by smujiang** [violet-sto/TGSA#3]
Hi, Thanks for sharing your wonderful work.
I'm able to replicate most of your results, but not able to regenerate the training data [cell_feature_all.npy](https://github.com/violet-sto/TGSA/blob/master/data/CellLines_DepMap/CCLE_580_18281/census_706/cell_feature_all.npy) using your code. Will appreciate it if you can provide more details.

**Comment by violet-sto** [comment]
Hi, we have provided the processed genetic data exp.csv, mu.csv, and cn.csv. You can use preprocess_gene.py to read these files and transform them into graph data with torch_geometric.

**Comment by smujiang** [comment]
Thanks for your prompt response.
But the code only generate cell_features_cn_std.npy. Is this file the same as cell_feature_all.npy?

**Comment by violet-sto** [comment]
We are sorry for the inconsistent file name. Indeed, this file is the same as cell_feature_all. In the l90-l100 of preprocess_gene.py, you can freely choose the genetic features of the cell graphs.

**Comment by smujiang** [comment]
> We are sorry for the inconsistent file name. Indeed, this file is the same as cell_feature_all. In the l90-l100 of preprocess_gene.py, you can freely choose the genetic features of the cell graphs.

Thanks for your detailed reply.
